name: "Mark Saroufim"
description: "My blog about machine learning, technology and philosophy"

url: "http://www.marksaroufim.com"

paginate: 10
markdown: kramdown
permalink: pretty
highlighter: pygments.rb
pages_list:
  About: '/about'
  Archive: '/archive'
  #LinkedIn/CV
  #Github

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']
